### ISSUE TITLE
logo.png contains copyrighted material without license to redistribute

### ISSUE THREAD

**Issue by kapouer** [samccone/monocle#22]
Hi,
if you have a look inside it:
`identify -verbose logo.png`
you'll see it contains

```
  Profiles:
    Profile-icc: 3144 bytes
      Description: sRGB IEC61966-2.1
      Manufacturer: IEC http://www.iec.ch
      Model: IEC 61966-2.1 Default RGB colour space - sRGB
      Copyright: Copyright (c) 1998 Hewlett-Packard Company
```

The copyrighted ICC profile has no license, hence you can't know if you're allowed to redistribute that file or not.
You can either edit the file, or just remove it.
